#!/usr/bin/env ansible-playbook
- name: Install Base Packages
  hosts: localhost
  become: true
  vars_files:
          - variables.yml
  tasks:
          - name: Ensure OS packages are installed
            package:
                    state: latest
                    name: "{{ packages.os }}"

          - name: Ensure PIP3 packages are installed
            pip:
                    executable: pip3
                    state: latest
                    name: "{{ packages.pip }}"
                
          - name: Ensure PIP packages are installed
            pip:
                    executable: pip
                    state: latest
                    name: "{{ packages.pip }}"

          - name: Ensure ansible-galaxy roles are installed
            command: ansible-galaxy install -r requirements.yml
            become: false