#!/usr/bin/env ansible-playbook
- name: Install Packages using Ansible-Galaxy Roles
  hosts: localhost
  become: true
  vars_files:
      - variables.yml
  roles:
    - role: gantsign.visual-studio-code
    - role: geerlingguy.docker
      vars:
        # Overrides for Linux Mint
        docker_apt_release_channel: stable
        docker_apt_arch: amd64
        docker_apt_repository: "deb [arch={{ docker_apt_arch }}] https://download.docker.com/linux/{{ override_ansible_distribution|lower }} {{ override_ansible_distribution_release }} {{ docker_apt_release_channel }}"
    - role: viasite-ansible.zsh
    - role: andrewrothstein.terraform
  tasks: []