# Ansible-Galaxy Roles to install
- src: gantsign.visual-studio-code
- src: geerlingguy.docker
- src: viasite-ansible.zsh
- src: andrewrothstein.terraform
- src: andrewrothstein.kubectl
- src: andrewrothstein.kubernetes-helm