---
# vars file for helm-plugins
helm_plugins:
  - name: helm-diff
    url: https://github.com/databus23/helm-diff
    version: master
  - name: helm-s3
    url: https://github.com/hypnoglow/helm-s3.git
    version: master